return {
    RemoveDefaultBaseplate = true,

    GroundSize = Vector3.new(768, 8, 768),
    GroundPosition = Vector3.new(0, -4, 0),

    SpawnPosition = Vector3.new(0, 4, 52),

    BillboardSize = Vector3.new(30, 16, 1.2),
    BillboardPosition = Vector3.new(0, 18, -38),
    BillboardBrightness = 2.8,

    SignText = "EXPEDICAO MASTERTECH",
    MarketingText = "Entre na nossa comunidade para acompanhar os desafios, eventos e novidades da expedicao.",

    GroupUrl = "https://www.roblox.com/communities/",
    WebsiteUrl = "https://roblox.mastertech.com.br",
}
